### ISSUE TITLE
Error in the creation of stratum_bf_deb.deb

### ISSUE THREAD

**Issue by fernnf** [stordis/APS-One-touch#12]
ERROR: /root/switch/stratum/stratum/hal/bin/barefoot/BUILD:42:18: Linking of rule '//stratum/hal/bin/barefoot:stratum_bf' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/stratum/hal/bin/barefoot/stratum_bf-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/stratum/hal/lib/barefoot/_objs/bf_sde_wrapper/bf_sde_wrapper.pic.o:bf_sde_wrapper.cc:function stratum::hal::barefoot::BfSdeWrapper::AddDevice(int, stratum::hal::barefoot::BfrtDeviceConfig const&): error: undefined reference to 'bfrt::BfRtDevMgr::getInstance()'
bazel-out/k8-fastbuild/bin/stratum/hal/lib/barefoot/_objs/bf_sde_wrapper/bf_sde_wrapper.pic.o:bf_sde_wrapper.cc:function stratum::hal::barefoot::BfSdeWrapper::AddDevice(int, stratum::hal::barefoot::BfrtDeviceConfig const&): error: undefined reference to 'bfrt::BfRtDevMgr::bfRtInfoGet(int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bfrt::BfRtInfo const**) const'
bazel-out/k8-fastbuild/bin/stratum/hal/lib/barefoot/_objs/bf_sde_wrapper/bf_sde_wrapper.pic.o:bf_sde_wrapper.cc:function stratum::hal::barefoot::BfSdeWrapper::Session::CreateSession(): error: undefined reference to 'bfrt::BfRtSession::sessionCreate()'
collect2: error: ld returned 1 exit status
Target //stratum/hal/bin/barefoot:stratum_bf_deb failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 164.774s, Critical Path: 56.67s
INFO: 1591 processes: 1591 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by fernnf** [comment]
Add on setting.yaml the build flag " - -rt"

**Comment by kamalkrbh** [comment]
@fernnf "- -rt" or more build flags(every other flag avialble in p4studio_build.py) can be added by user in the settings.yaml, the flags you see placed in settings.yaml are for example purpose.
For stratum build issue I will have look into it soon.

**Comment by kamalkrbh** [comment]
@fernnf Regarding Stratum build issue, The build procedure in AOT is for older Stratum releases, Looks stratum build procedure may change time to time and is a potential maintenance effort in AOT so I will recommend refering Stratum Github page for building with latest procedures and Stratum build support is removed from AOT.

Thanks,
Kamal K. Bhatt
