### ISSUE TITLE
Can't find env_var SWTICH_MODEL

### ISSUE THREAD

**Issue by LukasChenChen** [stordis/APS-One-touch#16]
Hi
When i try to invoke python3 bf_sde.py  with BF6064X_T.
ubuntu-18.04.5-server-amd64
9.4.0_AOT1.5.1_SAL1.3.2.zip
bf_sde 9.4.0.

after press yes to build bsp.
It keeps saying cant find SWITCH_MODEL.
But I already set up this by export SWITCH_MODEL=BF6064X_T.
it can be seen by typing "env".
I also tried with root but not working.
I think it won't be too difficult to reproduce this.

Many thanks if you could have a look at this.

chen

After modify the /etc/environment file it works. cheers.

**Comment by kamalkrbh** [comment]
Hello Chen,
are you invoking _python3 bf_sde.py_ with 'sudo' ? BTW you need not to.

Thanks,
Kamal K. Bhatt

**Comment by CommitThis** [comment]
No updates so closing.
