### ISSUE TITLE
Reqiured Software pip3 missing (Ubuntu 20.04.03) 

### ISSUE THREAD

**Issue by mlsgit** [stordis/APS-One-touch#21]
The list of required software is missing pip3 on ubunut 20.04.03. At least my installation didn't had it, even though I've followed the given list of required packages.

**Comment by CommitThis** [comment]
Hi @mlsgit, thanks for the issue. I will have a look, if it's not in the dependencies it should be added.

**Comment by ralfkundel** [comment]
this bug is present still in the current version of One-touch. installing it manually with apt solve it (package python3-pip)

**Comment by CommitThis** [comment]
AOT Deprecated in favour of Intel compatible BSP tarballs and Debian installer packages.
