### ISSUE TITLE
SAL: Cannot Configure 40G Ports

### ISSUE THREAD

**Issue by erhauser** [stordis/APS-One-touch#22]
When using the SAL to configure and enable ports, everything works seamlessly except for the `40G` port speed.

Using the following configuration in BloomRPC grpc client,

```json
{
  "portId": {
    "portNum": 49,
    "lane": 0
  },
  "portConf": {
    "speed": 7,
    "fec": 0,
    "an": 0,
    "fc": 0,
    "enable": 1,
    "up": 1
  }
}
```

the corresponding port 49/0 does not come up.
Verifying this with the bfshell shows the following result:

```
bf-sde.pm> show
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
PORT |MAC |D_P|P/PT|SPEED  |FEC |AN|KR|RDY|ADM|OPR|LPBK    |FRAMES RX       |FRAMES TX       |E
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
49/0 |20/0|156|3/28|-------|NONE|Au|Au|YES|ENB|DWN|  NONE  |               0|               0|
```

Instead, running the following commands to set up the port directly in the bfshell:

```
bf-sde.pm> port-add 49/0 40G none
bf-sde.pm> port-enb 49/0
```

The 40G port comes up as expected.

```
bf-sde.pm> show
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
PORT |MAC |D_P|P/PT|SPEED  |FEC |AN|KR|RDY|ADM|OPR|LPBK    |FRAMES RX       |FRAMES TX       |E
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
49/0 |20/0|156|3/28|40G    |NONE|Au|Au|YES|ENB|UP |  NONE  |               0|               0|
```

For some reason, the 40G port speed is set "-------" instead of "40G" when using the SAL.

I have observed this behavior for SAL configured 40 Gbit/s ports on the BF-SDE 9.5.0 and 9.7.0 with the SAL versions 1.3.4 and 1.3.5, respectively.

Could you please take a look at this problem so that I can also configure my 40 Gbit/s port also through the SAL?

**Comment by CommitThis** [comment]
Hello, sorry to be a pain, but could you either raise a ticket on the support portal, or send an email to support@aps-networks.com? We don't really track issues on GitHub, and much prefer to use our support system instead. Thanks.
