### ISSUE TITLE
Reference BSP 9.2.0 not available from Intel anymore

### ISSUE THREAD

**Issue by srieger1** [stordis/APS-One-touch#8]
The BF Reference BSP 9.2.0 is required by the current version of AOT. However, Intel only offers current Version 9.3.0. In the Intel Forums users already asked to also get older releases from the Barefoot era, but this seems to be not compliant with Intels quality assurance regulations. So I think currently one can only get the reference BSP in the most recent version 9.3.0.

Regards,

Sebastian

**Comment by kamalkrbh** [comment]
Please contact Intel support to get old versions of BSP, BSP 9.3 porting is in progress we will be releasing new AOT version soon.
