### ISSUE TITLE
All path in config file are relative to user home directory

### ISSUE THREAD

**Issue by ralfkundel** [stordis/APS-One-touch#9]
Hi,
while trying to install a tofino in /opt/bf-sde-9.3.0/... i found out that this is not possible easily.

The reason is: all path configurations in the yaml are relative to the current users home director ("get_path_relative_to_user_home").

Idea: if a path in the config file starts with a backslash("\") --> don't use the users home directory. In all other cases, i think it would be fine.

**Comment by kamalkrbh** [comment]
@ralfkundel Have you tried setting PATH_PREFIX in settings.yaml ? For your case if you set PATH_PREFIX to /opt/ or just '/' and give rest of the paths accordingly the get_path_relative_to_user_home function will append value of PATH_PREFIX instead of USER_HOME.

**Comment by ralfkundel** [comment]
Totally overseen. Thanks ;-)
